"""Serialize completed independent visual judgments; no model/GT/prediction reads."""
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent

def row(id, target, contact_status, contact_interval, side, lane_status, lane_interval,
        first_visible, evidence, limits, contact_confidence='low', lane_confidence='low', side_confidence='medium'):
    return dict(ID=id, counterpart_description=target,
        ego_vehicle_contact_status=contact_status,
        first_physical_contact=dict(exact_frame=None, interval=contact_interval,
            interval_kind='visually_suspected_event_window_not_exact_contact_GT' if contact_interval else 'unknown',
            confidence=contact_confidence),
        entry_side=side, entry_side_confidence=side_confidence if side else 'unknown',
        lane_entry=dict(status=lane_status, exact_frame=1 if lane_status=='already_in_ego_corridor_at_start' else None,
            interval=lane_interval, confidence=lane_confidence,
            definition='first target wheel touching ego lane boundary or visible intersection extension; never first screen appearance'),
        screen_first_visible_diagnostic_only=first_visible,
        evidence=evidence, limitations=limits,
        metric_eligibility=dict(exact_collision=False, exact_entry=lane_status=='already_in_ego_corridor_at_start',
            exact_entry_conditional_on_counterpart_and_contact_confirmation=lane_status=='already_in_ego_corridor_at_start',
            side_only_candidate=side is not None, requires_root_independent_consensus=True))

rows = [
row('DADA_10_120', '미확정. 73~94의 왼쪽 화면 가장자리 흰색 세단이 근접 후보이며 초반 흰색 SUV와 구분해야 함.',
    'not_discernible_from_reviewed_images', None, None, 'unknown', None,
    {'interval':None,'status':'target_identity_not_confirmed'},
    ['73/87/94에서 흰 세단 일부가 왼쪽 끝에 보이나 101 이후 화면 안 충돌 상대를 확인하지 못함.',
     '자차 시야가 오른쪽으로 회전하고 123에서 실내 장식이 크게 움직임. 이것만으로 어느 차량과 언제 접촉했는지 정할 수 없음.'],
    ['접촉이 왼쪽 화면 밖에서 일어났는지 확인 불가. 교차로 연장 차선과 상대 바퀴의 첫 접점도 불명.',
     '흰 세단의 LEFT 근접 위치를 확정된 entry_side로 대체하지 않음.']),
row('DADA_10_142', '155부터 왼쪽에서 가로질러 자차 앞에 들어오는 검정 세단. 초반 은색 해치백·앞서 지나간 빨간 세단과 다름.',
    'probable_ego_vehicle_contact_surface_occluded', [169,184], 'LEFT', 'interval_uncertain_lane_extension', [155,169],
    {'interval':[145,155],'status':'not_visible_at_145_visible_at_155'},
    ['155에서 검정 세단 앞부분이 왼쪽 화면에 등장하고 163~175 자차 바로 앞을 왼쪽→오른쪽으로 가로지름.',
     '169~184 동안 차체가 보닛 앞을 채우고 시야가 회전한 뒤 차량 뒤쪽을 보게 됨.'],
    ['접촉면이 보닛 아래에 가려져 첫 물리 접촉을 정확히 관찰하지 못함.',
     '교차로 차선 연장선이 명확하지 않아 155~169는 넓은 진입 검토구간이며 ±0.3초 정답으로 사용할 수 없음.'],
    'medium','low','high'),
row('DADA_11_045', '시작부터 자차 오른쪽에 나란히 있는 은색 세단. 앞의 검정 세단이나 반대편 빨간 화물차와 다름.',
    'probable_ego_vehicle_contact_surface_occluded', [81,100], 'RIGHT', 'interval_uncertain_wheel_boundary', [57,87],
    {'interval':[1,1],'status':'visible_at_start_not_equivalent_to_lane_entry'},
    ['1/30/45에서 은색 차량은 자차 오른쪽 차로의 경계 바깥쪽에 있음.',
     '57~87에 차량 앞바퀴와 차체가 자차 오른쪽 경계 방향으로 다가오며 보닛 오른쪽을 차지함.',
     '81~100 근접 이후 두 차량이 매우 가까운 상태로 이어짐.'],
    ['가장 가까운 바퀴·접촉면 일부가 보닛 아래에 가려져 최초 차선 접점과 접촉 시점의 정확한 번호는 불명.',
     '우측 차량이 처음부터 보인다는 이유로 entry=1을 부여하지 않음.'],
    'medium','medium','high'),
row('DADA_11_129', '시작부터 왼쪽 앞에 보이며 교차로를 가로질러 자차 앞을 통과하는 흰색 SUV.',
    'probable_ego_vehicle_contact_surface_occluded', [71,83], 'LEFT', 'interval_uncertain_lane_extension', [25,55],
    {'interval':[1,1],'status':'visible_at_start_outside_projected_ego_corridor'},
    ['1/25에서는 SUV가 자차 왼쪽 앞에 있고 35/45/55에서 자차 진행 공간을 가로지름.',
     '65~80에 SUV 옆면이 화면 바로 앞을 채우고 이후 자차 앞 오른쪽에 정지한 모습이 지속됨.'],
    ['표시 차선이 없는 교차로이고 자차 연장선 폭이 불명확하여 정확한 바퀴 접점을 정하지 못함.',
     'SUV가 이미 화면에 보이는 것과 차선 안에 있는 것은 다름. 접촉면은 화면 아래에 가려짐.'],
    'medium','low','high'),
row('DADA_49_002', '자차 정면을 선행하다 비스듬히 움직이는 빨간 대형 화물차가 장면의 주요 대상. 실제 충돌 상대인지는 미확정.',
    'not_discernible_from_reviewed_images', None, None, 'already_in_ego_corridor_at_start', [1,1],
    {'interval':[1,1],'status':'visible_at_start'},
    ['원본 1에서 화물차가 황색 중앙선 오른쪽의 자차 전방 진행 공간에 이미 있음.',
     '105~165 및 이후 화물차 후면과 자차 사이에 도로가 보이며 물리 접촉을 식별하지 못함.'],
    ['조건부 대상이 이 화물차라면 entry=첫 프레임이지만 ego-vehicle 충돌 여부를 먼저 확인해야 함.',
     '화물차의 이후 회전 방향으로 시작 전 진입측을 복원할 수 없음.'],
    'unknown','medium'),
row('DADA_49_015', '왼쪽의 녹색 대형 화물차가 오른쪽으로 이동. 정면의 붉은 소형 세단도 근접하며 실제 ego 충돌 상대는 미확정.',
    'not_discernible_from_reviewed_images', None, 'LEFT', 'interval_conditional_on_green_truck_target', [247,310],
    {'interval':[1,1],'status':'green_truck_visible_at_start_in_left_adjacent_lane'},
    ['1~247 녹색 화물차가 자차 왼쪽, 붉은 세단이 정면에 있음.',
     '247~310 화물차 후면이 자차 전방 공간으로 이동하고 붉은 세단은 그 오른쪽으로 밀집됨.',
     '검토한 장면에서 자차와 화물차 또는 붉은 세단의 물리 접촉을 식별하지 못함.'],
    ['LEFT는 녹색 화물차를 대상으로 한 조건부 기원측. 확정 충돌 상대 라벨이 아님.',
     '화물차/붉은 세단 사이의 접촉 여부도 충분히 보이지 않아 제3자 사고로 확정하지 않음.'],
    'unknown','low','medium'),
row('DADA_50_031', '정면의 은색 Volkswagen 해치백/MPV가 선행 대상. 오른쪽의 검정 가로방향 세단과 혼동하지 않아야 함.',
    'possible_ego_rear_contact_not_visually_resolved', [181,226], None, 'already_in_ego_corridor_at_start', [1,1],
    {'interval':[1,1],'status':'visible_at_start'},
    ['1에서 은색 차량이 자차 정면 진행 공간에 있고 154 이후 브레이크등이 켜진 상태로 가까워짐.',
     '181~226 은색 차량 후면이 커지지만 정확한 범퍼 접점이나 접촉 순간은 보닛 아래에 가림.'],
    ['접촉은 가능 구간에 불과하며 사고 GT로 인정하지 않음.',
     '대상이 은색 선행차이고 실제 ego 접촉이 확인될 경우 entry=첫 프레임으로 조건부 판단. 이전 진입측은 불명.'],
    'low','medium'),
row('DADA_50_172', '노란색/파란색 택시와 오른쪽 오토바이가 선행하지만 ego 충돌 상대를 식별하지 못함.',
    'not_discernible_from_reviewed_images', None, None, 'unknown', None,
    {'interval':None,'status':'counterpart_unknown_several_vehicles_visible_at_start'},
    ['194~254 택시와 오토바이는 자차 앞에 거리를 두고 보임.',
     '뒤쪽 구간에서는 보행자가 횡단하며 자차와 특정 차량의 직접 접촉을 식별하지 못함.'],
    ['택시·오토바이·다른 차량 중 대상을 추정해서 차선진입/접촉 라벨을 강제하지 않음.',
     '접촉을 못 본 것과 무충돌임을 증명한 것은 다름.']),
row('DADA_8_036', '왼쪽에서 교차로를 가로질러 접근하는 주황색 소형 화물차/삼륜 화물차.',
    'strong_visual_sequence_evidence_of_ego_vehicle_impact', [119,125], 'LEFT', 'interval_uncertain_lane_extension', [102,120],
    {'interval':None,'status':'distant_target_visible_before_90_exact_first_appearance_not_assigned'},
    ['90~114 주황색 화물차가 왼쪽에서 자차 전방으로 접근함.',
     '119~123 차량 앞부분이 자차 왼쪽 보닛 바로 앞을 채우면서 시야가 급격히 움직이고 125에서 실내 물체가 튀어 보임.'],
    ['직접 접촉면 일부는 보닛 아래/왼쪽 화면 밖에 있어 정확한 한 프레임은 부여하지 않음.',
     '교차로 바퀴-차선 연장 접점은 명확하지 않아 102~120은 넓은 시각구간.'],
    'high','low','high'),
row('DADA_8_039', '시작부터 오른쪽 차로에 있는 파란 소형 평판 화물차가 후반 자차 정면의 근접 대상. 정면 빨간 해치백과 다름.',
    'probable_ego_vehicle_contact_surface_occluded', [236,251], 'RIGHT', 'unknown_ego_turn_and_target_motion_confound', None,
    {'interval':[1,1],'status':'visible_at_start_in_right_adjacent_lane'},
    ['원본 1에서 빨간 해치백이 자차 정면 차로, 파란 화물차가 오른쪽 인접 차로에 있음.',
     '160~238에 시야가 우회전 방향으로 변하며 파란 화물차가 정면을 차지하고 238~242 실내 물체가 크게 움직임.'],
    ['파란 차량의 차선 변경과 자차 경로 변화의 기여를 분리하지 못해 최초 바퀴 진입구간은 unknown.',
     'RIGHT는 관찰 가능한 이전 상대 위치에 근거하지만 교차로 차로 연장과 함께 root 합의가 필요.',
     '급격한 실내 움직임이 접촉 시점 그 자체임을 보장하지 않음.'],
    'medium','unknown','medium'),
row('DADA_9_001', '왼쪽에서 자차를 추월해 앞으로 들어오는 짙은 회색 소형 평판 화물차.',
    'probable_close_ego_side_interaction_contact_not_resolved', [114,132], 'LEFT', 'interval_uncertain_unmarked_road', [103,132],
    {'interval':[88,93],'status':'not_visible_at_88_visible_at_93'},
    ['93~110 화물차가 왼쪽 가까이 나타나고 117~132 자차 앞쪽을 가로막으며 이후 선행함.',
     '우측은 풀·경사면 경계인 좁은 도로이며 도색 차선이 보이지 않음.'],
    ['도로폭과 자차 차선의 실제 경계가 불명확하고 가까운 바퀴가 보닛/화면 하단에 가려짐.',
     '좁은 간격과 경로 중첩은 보이지만 접촉면을 직접 식별하지 못함.'],
    'low','low','high'),
row('DADA_9_009', '1차 근접 대상은 오른쪽 검정 세단. 뒤이어 왼쪽 노란 대형 화물차가 매우 가깝게 들어오므로 다중 상호작용 구분 필요.',
    'strong_visual_sequence_evidence_multiple_ego_vehicle_interactions', [211,250], 'RIGHT', 'interval_uncertain_wheel_boundary', [185,215],
    {'interval':None,'status':'black_sedan_already_visible_by_124_exact_initial_identity_not_traced'},
    ['145~205 검정 세단이 오른쪽에서 자차 앞/옆으로 가까워지며 211~223 화면 오른쪽 가장자리에 밀집됨.',
     '226 이후 노란 화물차가 왼쪽에서 들어오고 242에 막대 모양 부품이 화면 하단 앞으로 돌출되는 별도 위험 장면이 있음.'],
    ['검정 세단과의 첫 물리 접촉을 화면 아래에서 직접 확인하지 못해 두 사건 중 어떤 것이 첫 접촉인지 불확실.',
     '211~250은 다중 사건 검토 창이지 ±0.3초 접촉 정답이 아님.',
     'RIGHT는 검정 세단을 1차 대상으로 보는 조건부 기원측. 노란 화물차를 대상으로 하면 LEFT이므로 target 합의가 필수.'],
    'medium','low','medium'),
]

reviewed = sorted([p for p in HERE.glob('*.jpg') if p.name.startswith('DADA_') or p.name.startswith('agent1_')])
payload = {
    'reviewer': 'agent1 / stage1_research',
    'review_type': 'independent AI visual review, NOT official ground truth',
    'frozen_before_root_consensus_at_utc': datetime.now(timezone.utc).isoformat(),
    'prediction_files_read': False, 'model_inference_used': False,
    'provided_accident_frame_metadata_read': False,
    'material': '12 supplied overview + 12 supplied contact sheets, 10 own detail sheets, four enlarged frame-1 PNGs',
    'frame_numbering': 'original supplied 1-based PNG filenames; supplied 30fps convention only, no model timing assumptions',
    'interval_semantics': 'inclusive visual uncertainty windows, not exact frame GT; wide/low-confidence windows must not be treated as scoring positives',
    'contact_semantics': 'not_discernible does not assert no collision; probable/strong sequence evidence is distinguished from directly resolved physical contact',
    'lane_semantics': 'first wheel touching ego lane or visible intersection extension; visibility at frame 1 alone never implies entry=1',
    'scope_caution': 'conditional target/entry labels require independent root consensus before evaluating any predictions',
    'reviewed_sheet_sha256': {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in reviewed},
    'additional_enlarged_original_frames': ['DADA_11_045/0001.png','DADA_11_129/0001.png','DADA_49_002/0001.png','DADA_8_039/0001.png'],
    'labels': rows,
}
target = HERE / 'agent1_labels.json'
if target.exists():
    raise RuntimeError('Do not overwrite independently frozen review')
target.write_text(json.dumps(payload,ensure_ascii=False,indent=2),encoding='utf-8')
md = ['# DADA 12개 영상: 독립 AI 시각 검토', '',
      '**공식 GT가 아니다. V3/V5 예측 파일과 제공 accident_frame 메타데이터를 열지 않고 검토했다.** root의 독립 검토와 합의 전 동결본이다.', '',
      'frame은 원본 PNG의 1-based 번호다. interval은 시각적 불확실성 구간이며 중앙값을 정답으로 만들면 안 된다. 접촉 미식별은 무충돌 확정이 아니다. probable은 접촉면이 가려진 추정이고 강한 영상상 근거와 구분했다.', '',
      '진입은 바퀴가 자차 차선/교차로 연장선에 처음 닿는 시점이다. 화면 등장 시점은 별도 진단에만 기록했다. 처음부터 보이는 차량을 일괄 entry=1로 처리하지 않았다.', '',
      '| 영상 | 대상 | 차선진입 | 진입측 | 첫 접촉 검토구간 |', '|---|---|---|---|---|']
for r in rows:
    md.append(f"| {r['ID']} | {r['counterpart_description']} | {r['lane_entry']['status']} / {r['lane_entry']['interval']} | {r['entry_side'] or 'unknown'} | {r['first_physical_contact']['interval'] or 'unknown'} |")
for r in rows:
    md += ['', f"## {r['ID']}", '', f"접촉 판단: `{r['ego_vehicle_contact_status']}`. 정확한 접촉 프레임은 부여하지 않았다.", '',
           *['- '+v for v in r['evidence']], '', '한계:', '', *['- '+v for v in r['limitations']]]
md += ['', '조건부 entry=1은 49_002의 빨간 선행 화물차와 50_031의 은색 선행차 두 항목뿐이다. 이들도 실제 ego 충돌 상대 여부가 먼저 합의돼야 한다. 넓은/저신뢰 진입·접촉 구간은 ±0.3초 정확도 정답으로 사용하지 않는다.', '',
       'DADA_9_009는 오른쪽 세단과 왼쪽 화물차의 다중 사건이 있어 하나의 방향·접촉 라벨로 묶기 전 대상 선정이 필요하다. DADA_10_120·49_002·49_015·50_172는 ego-vehicle 물리 접촉을 분명히 식별하지 못했다. 대회 동질성 표본으로 자동 편입하지 않는다.', '',
       '전체 판단·근거·신뢰도·검토 sheet SHA는 agent1_labels.json에 보존했다. 이후 root 합의는 이 독립본을 덮어쓰지 않고 별도로 기록한다.']
(HERE / 'agent1_labels.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print(json.dumps({'labels':len(rows),'sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'frozen_at':payload['frozen_before_root_consensus_at_utc']}))
